---
title: "Wheat_IPM"
author: "Mitch Roth"
date: "5/14/2020"
output: html_document
---

```{r, import data}
master.df <- read.csv2("wheat_IM_data.csv", sep = ",", header = T)
colnames(master.df)
master.df$Year <- as.factor(master.df$Year)
master.df$weight_lbs <- as.numeric(as.character(master.df$weight_lbs))
master.df$Percent_Moisture <- 
  as.numeric(as.character(master.df$Percent_Moisture))
master.df$Yield_bushels_acre <- 
  as.numeric(as.character(master.df$Yield_bushels_acre))
master.df$Yield_kg_hect <- as.numeric(as.character(master.df$Yield_kg_hect))
master.df$Test_weight_kg_hL <- 
  as.numeric(as.character(master.df$Test_weight_kg_hL))
master.df$seed_weight_250g <- 
  as.numeric(as.character(master.df$seed_weight_250g))
master.df$TKW_g <- as.numeric(as.character(master.df$TKW_g))

#Disease data
master.df$Stripe_Rust_DI <- as.numeric(master.df$Stripe_Rust_DI)
master.df$Stripe_Rust_DI_beta <- master.df$Stripe_Rust_DI/100
master.df$Stripe_Rust_DS <- as.numeric(master.df$Stripe_Rust_DS)
master.df$Stripe_Rust_DS_beta <- master.df$Stripe_Rust_DS/80

master.df$FHB_DI <- as.numeric(master.df$FHB_DI)
master.df$FHB_DI_beta <- master.df$FHB_DI/15
master.df$FHB_DS <- as.numeric(master.df$FHB_DS)
master.df$FHB_DS_beta <- master.df$FHB_DS/45
master.df$DON_ppm <- as.numeric(as.character(master.df$DON_ppm))
master.df$DON_ppm <- master.df$DON_ppm + 0.001
master.df$DON_ppm_log <- log(master.df$DON_ppm)
colnames(master.df)
```

```{r, Acres planted}
planted.df <- read.csv2("planted_acres_yield_price.csv", 
                        sep = ",", header = T)
planted.df$Year
planted.df$WHEAT_ACRES_PLANTED <-
  as.numeric(as.character(planted.df$WHEAT_ACRES_PLANTED))
planted.df$WHEAT_BUSHELS_PRODUCED
planted.df$WHEAT_PRICE_RECIEVED_USD_BUSHEL <- 
  as.numeric(as.character(planted.df$WHEAT_PRICE_RECIEVED_USD_BUSHEL))
#Convert acres planted to hectares (divide acres by 2.471)
planted.df$WHEAT_HECTARES_PLANTED <- planted.df$WHEAT_ACRES_PLANTED/2.471
#Divide by 1 thousand to get in decent units
planted.df$WHEAT_HECTARES_PLANTED <- planted.df$WHEAT_HECTARES_PLANTED/1000000
#Convert bushels produced to tonnes (divide bushel by 36.74)
planted.df$WHEAT_TONNES_PRODUCED <- planted.df$WHEAT_BUSHELS_PRODUCED/36.74
#Divide by 1 million to get in decent units
planted.df$WHEAT_TONNES_PRODUCED <- planted.df$WHEAT_TONNES_PRODUCED/1000000
library(ggplot2)
ggplot(planted.df, aes(x=Year)) +
  geom_point(aes(y = WHEAT_HECTARES_PLANTED), size = 5, shape = 16) +
  stat_smooth(aes(y = WHEAT_HECTARES_PLANTED), 
              method = "lm", formula = y ~ x + I(x^2), 
              colour = "black", linetype = 1, size = 2) +
  #geom_text(x=2017, y=16.5, label="y = -0.33x + 682.0 \n P < 0.001",
  #          size = 8) +
  geom_point(aes(y = WHEAT_TONNES_PRODUCED/2), size = 5, shape = 17, 
             colour = "grey60") +
  geom_abline(slope = (-0.09773083/2), intercept = (252.85130202/2),
              colour = "grey60", linetype = 2, size = 1) +
  #geom_text(x=2017.5, y=32, label="y = -0.10x + 252.9 \n P = 0.68",
  #          colour = "grey60", size = 8) +
  ylab("Wheat hectares planted (millions)") +
  scale_y_continuous(sec.axis = sec_axis(~.*2, name = "Wheat production (millions of tonnes)")) +
  theme_bw() + theme(strip.text.x = element_text(size=8, face = "bold"),
                     axis.text.x=element_text(size=24),
                     axis.text.y=element_text(size=24),
                     axis.title.x=element_text(size=28, face="bold"),
                     axis.title.y=element_text(size=28, face="bold"))

plant.lm <- lm(WHEAT_HECTARES_PLANTED~Year, planted.df)
summary(plant.lm)
planted.df$Year2 <- planted.df$Year^2
plant.quad <- lm(WHEAT_HECTARES_PLANTED~Year + Year2, planted.df)
summary(plant.quad)
#Quadratic fit is better for hectares planted

yield.lm <- lm(WHEAT_TONNES_PRODUCED~Year, planted.df)
summary(yield.lm)
yield.lm$coefficients
yield.quad <- lm(WHEAT_TONNES_PRODUCED~Year + Year2, planted.df)
summary(yield.quad)
planted.df$Year3 <- planted.df$Year^3
yield.cubic <- lm(WHEAT_TONNES_PRODUCED~Year + Year2 + Year3, planted.df)
summary(yield.cubic)
```

```{r, get means, stats}
colnames(master.df)
#Use this function to get variety x management x year means
#Just replace "Pro 200" with whatever variety you're interested in
get_mean <- function(var, man, yr) {
  temp.df <- with(master.df, master.df[variety == as.character(var) & 
                                       management == as.character(man) &
                                       Year == as.character(yr),])
  mean(na.omit(temp.df$Test_weight_kg_hL))
}
get_mean("Pro 200","Current","2016")
get_mean("Pro 200","MidLevel","2016")
get_mean("Pro 200","HighLevel","2016")
get_mean("Pro 200","Current","2017")
get_mean("Pro 200","MidLevel","2017")
get_mean("Pro 200","HighLevel","2017")
get_mean("Pro 200","Current","2018")
get_mean("Pro 200","MidLevel","2018")
get_mean("Pro 200","HighLevel","2018")
get_mean("Pro 200","Current","2019")
get_mean("Pro 200","MidLevel","2019")
get_mean("Pro 200","HighLevel","2019")

#Use this function to variety means across years
#Just replace "Pro 200" with whatever variety you're interested in
get_mean2 <- function(var) {
  temp.df <- with(master.df, master.df[variety == as.character(var),])
  mean(na.omit(temp.df$Test_weight_kg_hL))
}
get_mean2("Pro 200")

#Get Tukey group letters for management effects of variety within year
#Just replace "Pro 200" with whatever variety you're interested in
AOVTukey <- function(var, yr) {
  temp.df <- with(master.df, master.df[variety == as.character(var) &
                                       Year == as.character(yr),])
  nova <- aov(Test_weight_kg_hL ~ management, data = temp.df)
  TukeyHSD(nova, ordered = TRUE)
}
AOVTukey("Pro 200", "2016")
AOVTukey("Pro 200", "2017")
AOVTukey("Pro 200", "2018")
AOVTukey("Pro 200", "2019")

#Get Tukey group letters for variety effects across years
library(emmeans)
library(multcomp)
allvar_lm <- lm(Test_weight_kg_hL ~ variety, data = master.df)
allvar_anova <- emmeans(allvar_lm, ~variety)
allvar_anova_results <- multcomp::cld(allvar_anova, 
                            alpha = 0.05, 
                            adjust = "tuk", 
                            Letters = letters, 
                            reversed = TRUE, 
                            details = TRUE)
allvar_anova_results
```


```{r, Yield}
#Examine if data can be combined across years
yield.aov <- aov(Yield_kg_hect ~ Year, data = master.df)
summary(yield.aov)
TukeyHSD(yield.aov)
#Significantly higher yields in 2016 than in any other year. Check test weight too
TW.aov <- aov(Test_weight_kg_hL ~ Year, data = master.df)
summary(TW.aov)
TukeyHSD(TW.aov)
#Incorporate this info into the data frame for plotting
master.df$Year
master.df$YearTukey <- rep(c("A","B","B","B"), each = 168)
master.df$Test_weight_kg_hL
master.df$Test_weight_kg_hLTukey <- rep(c("A","C","B","C"), each = 168)
library(ggplot2)
library(ggpubr)
#install.packages("forcats")
#install.packages("rstatix")
library(forcats)
library(rstatix)
colnames(master.df)
master.df$management <- fct_relevel(master.df$management,
                                    "Current","MidLevel","HighLevel")
treatments <- list(c("Current", "MidLevel"),
                   c("Current", "HighLevel"),
                   c("MidLevel", "HighLevel"))

symnum.args <- list(
  cutpoints = c(0, 0.001, 0.01, 0.05, 1), 
  symbols = c("***","**","*","ns"))

p1 <- ggplot(data = master.df, aes(x = management, y = Yield_kg_hect/1000, 
                             fill = management)) +
  stat_summary(fun = mean, position="identity", geom = "bar") +
  stat_summary(fun.data = mean_se, 
               position = "identity", 
               geom = "errorbar",
               width = 0.5) +
  stat_compare_means(comparisons = treatments, 
                     size = 5, label = "p.adj.signif", method = "t.test",
                     label.y = c(11,12.5,14), symnum.args = symnum.args) +
  geom_jitter(width = 0.1, alpha = 0.5) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  facet_grid(~Year + YearTukey, switch="x") +
  ylab("Yield\n(thousands of kg / hectare)") +
  #ggtitle("") +
  theme_bw() + guides(fill=guide_legend("Management Intensity")) +
  theme(legend.position="none",
          legend.title=element_text(size=24),
          legend.text=element_text(size=24),
          strip.text.x = element_text(size=20, face = "bold"),
          axis.text.x=element_blank(), 
          axis.text.y=element_text(size=20),
          axis.title.x=element_blank(), 
          axis.title.y=element_text(size=20, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank()) +
  scale_fill_grey()

p2 <- ggplot(data = master.df, aes(x = management, y = Test_weight_kg_hL, 
                             fill = management)) +
  stat_summary(fun = mean, position="identity", geom = "bar") +
  stat_summary(fun.data = mean_se, 
               position = "identity", 
               geom = "errorbar",
               width = 0.5) +
  stat_compare_means(comparisons = treatments, 
                     size = 5, label = "p.signif", method = "t.test",
                     label.y = c(85,95,107), symnum.args = symnum.args) +
  geom_jitter(width = 0.1, alpha = 0.5) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  geom_hline(aes(yintercept=75), linetype = 2) +
  facet_grid(~Year + Test_weight_kg_hLTukey, switch="x") +
  ylab("Wheat test weight\n(kg / hectaliter)") +
  #ggtitle("") +
  theme_bw() + guides(fill=guide_legend("Management Intensity")) +
  theme(legend.position="bottom",
          legend.title=element_text(size=24),
          legend.text=element_text(size=24),
          strip.text.x = element_text(size=20, face = "bold"),
          axis.text.x=element_blank(), 
          axis.text.y=element_text(size=20),
          axis.title.x=element_blank(), 
          axis.title.y=element_text(size=20, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank()) +
  scale_fill_grey()

library(gridExtra)
grid.arrange(p1,p2,ncol=1)
```

```{r, test weight docking probability}
colnames(master.df)
get.prob <- function(man) {
  temp.df <- master.df[master.df$management == as.character(man),]
  n <- length(temp.df$Test_weight_lbs_bu)
  nodock_count <- 0
  dock1_count <- 0
  dock2_count <- 0
  dock3_count <- 0
  for (i in temp.df$Test_weight_lbs_bu){
    if (i >= 58){
      nodock_count <- nodock_count + 1
    }
    else if (i < 58 && i >= 56){
      dock1_count <- dock1_count + 1
    }
    else if (i < 56 && i >= 52){
      dock2_count <- dock2_count + 1
    }
    else if (i < 52){
      dock3_count <- dock3_count + 1
    }
  }
  print(cat("No dock = ", nodock_count, " out of ", n))
  print(cat("Dock 1  = ", dock1_count, " out of ", n))
  print(cat("Dock 2  = ", dock2_count, " out of ", n))
  print(cat("Dock 3  = ", dock3_count, " out of ", n))
}
get.prob("Current")
get.prob("MidLevel")
get.prob("HighLevel")
```

```{r, DON docking probability}
colnames(master.df)
range(na.omit(master.df$DON_ppm))
get.prob2 <- function(man) {
  temp.df <- master.df[master.df$management == as.character(man),]
  n <- length(na.omit(temp.df$DON_ppm))
  nodock_count <- 0
  dock20_count <- 0
  dock30_count <- 0
  dock40_count <- 0
  for (i in na.omit(temp.df$DON_ppm)){
    if (i < 2.1){
      nodock_count <- nodock_count + 1
    }
    else if (i >= 2.1 && i < 3.0){
      dock20_count <- dock20_count + 1
    }
    else if (i >= 3.1 && i < 4.0){
      dock30_count <- dock30_count + 1
    }
    else if (i >= 4.0){
      dock40_count <- dock40_count + 1
    }
  }
  print(cat("No dock = ", nodock_count, " out of ", n))
  print(cat("Dock 20¢ = ", dock20_count, " out of ", n))
  print(cat("Dock 30¢ = ", dock30_count, " out of ", n))
  print(cat("Rejection = ", dock40_count, " out of ", n))
}
get.prob2("Current")
get.prob2("MidLevel")
get.prob2("HighLevel")
```


```{r, disease}
library(ggplot2)
library(ggpubr)
#install.packages("forcats")
library(forcats)
colnames(master.df)
master.df$management <- fct_relevel(master.df$management,
                                    "Current","MidLevel","HighLevel")
treatments <- list(c("Current", "MidLevel"),
                   c("Current", "HighLevel"),
                   c("MidLevel", "HighLevel"))

master.df2 <- master.df[master.df$Year != 2016,]

symnum.args <- list(
  cutpoints = c(0, 0.001, 0.01, 0.05, 1), 
  symbols = c("***","**","*","ns"))

p.FHB.DI <- ggplot(data = master.df2, aes(x = management, y = FHB_DI_beta, 
                             fill = management)) +
  stat_summary(fun = mean, position="identity", geom = "bar") +
  stat_summary(fun.data = mean_se, 
               position = "identity", 
               geom = "errorbar",
               width = 0.5) +
  stat_compare_means(comparisons = treatments, 
                     size = 5, label = "p.signif", method = "t.test",
                     label.y = c(1.2,1.4,1.6), symnum.args = symnum.args) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  scale_x_discrete(limits=c("HighLevel", "MidLevel", "Current")) +
  #scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  #facet_grid(~Year, switch="x") +
  ylab("FHB disease incidence") + xlab("") +
  coord_flip() +
  #ggtitle("") +
  theme_bw() + guides(fill=guide_legend("Management Intensity")) +
  theme(legend.position="none",
          legend.title=element_text(size=24),
          legend.text=element_text(size=24),
          strip.text.y = element_blank(),
          #strip.text.x = element_text(size=12, face = "bold"),
          axis.text.x=element_text(size=20),
          axis.text.y=element_text(size=20),
          axis.title.x=element_text(size=20, face="bold"),
          axis.title.y=element_text(size=20, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank()) +
  scale_fill_grey()

p.FHB.DS <- ggplot(data = master.df2, aes(x = management, y = FHB_DS_beta, 
                             fill = management)) +
  stat_summary(fun = mean, position="identity", geom = "bar") +
  stat_summary(fun.data = mean_se, 
               position = "identity", 
               geom = "errorbar",
               width = 0.5) +
  stat_compare_means(comparisons = treatments, 
                     size = 5, label = "p.signif", method = "t.test",
                     label.y = c(1.2,1.4,1.6), symnum.args = symnum.args) +
  geom_jitter(width = 0.2, alpha = 0.5) +
  scale_x_discrete(limits=c("HighLevel", "MidLevel", "Current")) +
  #scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  #facet_grid(~Year, switch="x") +
  ylab("FHB disease severity") + xlab("") +
  coord_flip() +
  #ggtitle("") +
  theme_bw() + guides(fill=guide_legend("Management Intensity")) +
  theme(legend.position="none",
          legend.title=element_text(size=24),
          legend.text=element_text(size=24),
          strip.text.y = element_blank(),
          #strip.text.x = element_text(size=12, face = "bold"),
          axis.text.x=element_text(size=20),
          axis.text.y=element_blank(),
          axis.title.x=element_text(size=20, face="bold"),
          axis.title.y=element_text(size=20, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank()) +
  scale_fill_grey()

master.df2 <- master.df2[master.df2$Year != 2017,]
p.DON <- ggplot(data = master.df2, aes(x = management, y = DON_ppm, 
                             fill = management)) +
  stat_summary(fun = mean, position="identity", geom = "bar") +
  stat_summary(fun.data = mean_se, 
               position = "identity", 
               geom = "errorbar",
               width = 0.5) +
  stat_compare_means(comparisons = treatments, 
                     size = 5, label = "p.signif", method = "t.test",
                     label.y = c(4.5,5.5,6.5), symnum.args = symnum.args) +
  geom_jitter(width = 0.1, alpha = 0.5) +
  scale_x_discrete(limits=c("HighLevel", "MidLevel", "Current")) +
  #scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
  #facet_grid(~Year) +
  ylab("DON concentrations (ppm)") + xlab("") +
  coord_flip() +
  #ggtitle("") +
  theme_bw() + guides(fill=guide_legend("Management Intensity")) +
  theme(legend.position="none",
          legend.title=element_text(size=24),
          legend.text=element_text(size=24),
          strip.text.y = element_blank(),
          #strip.text.x = element_text(size=12, face = "bold"),
          axis.text.x=element_text(size=20),
          axis.text.y=element_blank(),
          axis.title.x=element_text(size=20, face="bold"),
          axis.title.y=element_text(size=20, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank()) +
  scale_fill_grey()

master.df3 <- master.df[master.df$Year == 2017,]

p.SR.DS <- ggplot(data = master.df3, aes(x = management, 
                              y = Stripe_Rust_DS_beta, 
                              fill = management)) +
  stat_summary(fun = mean, position="identity", geom = "bar") +
  stat_summary(fun.data = mean_se, 
               position = "identity", 
               geom = "errorbar",
               width = 0.5) +
  stat_compare_means(comparisons = treatments, 
                     size = 5, label = "p.signif", method = "t.test",
                     label.y = c(1.2,1.4,1.6), symnum.args = symnum.args) +
  geom_jitter(width = 0.1, alpha = 0.5) +
  scale_x_discrete(limits=c("HighLevel", "MidLevel", "Current")) +
  #scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  #facet_grid(~Year) +
  ylab("Stripe rust\ndisease severity") + xlab("") +
  coord_flip() +
  #ggtitle("") +
  theme_bw() + guides(fill=guide_legend("Management Intensity")) +
  theme(legend.position="none",
          legend.title=element_text(size=24),
          legend.text=element_text(size=24),
          strip.text.y = element_blank(),
          #strip.text.x = element_text(size=12, face = "bold"),
          axis.text.x=element_text(size=20),
          axis.text.y=element_blank(),
          axis.title.x=element_text(size=20, face="bold"),
          axis.title.y=element_text(size=20, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank()) +
  scale_fill_grey()

p.SR.DI <- ggplot(data = master.df3, aes(x = management, 
                              y = Stripe_Rust_DI_beta, 
                              fill = management)) +
  stat_summary(fun = mean, position="identity", geom = "bar") +
  stat_summary(fun.data = mean_se, 
               position = "identity", 
               geom = "errorbar",
               width = 0.5) +
  stat_compare_means(comparisons = treatments, 
                     size = 5, label = "p.signif", method = "t.test",
                     label.y = c(1.2,1.4,1.6), symnum.args = symnum.args) +
  geom_jitter(width = 0.1, alpha = 0.5) +
  scale_x_discrete(limits=c("HighLevel", "MidLevel", "Current")) +
  #scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
  #facet_grid(~Year) +
  ylab("Stripe rust\ndisease incidence") + xlab("") +
  coord_flip() +
  #ggtitle("") +
  theme_bw() + guides(fill=guide_legend("Management Intensity")) +
  theme(legend.position="none",
          legend.title=element_text(size=24),
          legend.text=element_text(size=24),
          strip.text.y = element_blank(),
          #strip.text.x = element_text(size=12, face = "bold"),
          axis.text.x=element_text(size=20),
          axis.text.y=element_text(size=20),
          axis.title.x=element_text(size=20, face="bold"),
          axis.title.y=element_text(size=20, face="bold"), 
          axis.ticks.x=element_blank(),
          panel.background=element_blank()) +
  scale_fill_grey()

#install.packages("patchwork")
library(patchwork)
layout <- "
AABB##
CCDDEE
"
p.SR.DI + p.SR.DS + p.FHB.DI + p.FHB.DS + p.DON +
  plot_layout(design = layout)
```

